sonar.projectKey=welt13_CoreKit
sonar.organization=welt13
sonar.projectName=CoreKit
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
